name: Update Env and Deploy

on:
  schedule:
    - cron: '0 0 * * *' # 每天执行一次
  workflow_dispatch: # 手动触发

jobs:
  update-env-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate new access code
      id: generate-code
      run: |
        new_access_code=$(date +%Y%m%d%H%M%S | sha256sum | base64 | head -c 12)
        echo "new_access_code=$new_access_code" >> $GITHUB_ENV
        echo "The new access code is $new_access_code"  # 输出到日志

    - name: Update Vercel Project environment variable
      env:
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
        NEW_ACCESS_CODE: ${{ env.new_access_code }}
      run: |
        curl -X PATCH "https://api.vercel.com/v10/projects/$VERCEL_PROJECT_ID/env" \
          -H "Authorization: Bearer $VERCEL_API_TOKEN" \
          -H "Content-Type: application/json" \
          -d '[
                {
                  "key": "ACCESS_CODE",
                  "value": "'"$NEW_ACCESS_CODE"'",
                  "target": ["production", "preview", "development"]
                }
              ]'
        echo "Updated Vercel environment variable ACCESS_CODE with value: $NEW_ACCESS_CODE"

    - name: Trigger redeployment for Vercel project
      env:
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
      run: |
        curl -X POST "https://api.vercel.com/v13/deployments" \
          -H "Authorization: Bearer $VERCEL_API_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
                "name": "Vercel Deployment",
                "projectId": "'$VERCEL_PROJECT_ID'"
              }'
        echo "Triggered redeployment for Vercel project with ID: $VERCEL_PROJECT_ID"

    - name: Send email with new access code
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_SERVER_ADDRESS }}
        server_port: ${{ secrets.SMTP_SERVER_PORT }}
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "New Access Code for Vercel Project"
        to: ${{ secrets.ADMIN_EMAIL }}
        body: "The new access code is ${{ env.new_access_code }}"
        from: ${{ secrets.EMAIL_FROM }}
